version: "3.9"

networks:
  proxy-network:
    external: false
    name: proxy-network
  server-network:
    driver: bridge

services:
  postgres:
    image: postgres:13.1
    container_name: postgres
    restart: always
    networks:
      - server-network
      - proxy-network
    ports:
      - 5432:5432
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6.0.9
    container_name: redis
    restart: always
    networks:
      - server-network
      - proxy-network
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    env_file: .env
    networks:
      - server-network
      - proxy-network
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: always
    networks:
      - server-network
      - proxy-network
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID:-root}
    volumes:
      - ./vault-data:/vault/file
    privileged: true
