# Start vault server locally for the purposes of integration tests.
version: "3.0"
services:
  vault:
    image: hashicorp/vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
    ports:
      - 8200:8200
    privileged: true
