version: "3.9"

networks:
  proxy-network:
    external: false
    name: proxy-network

services:
  traefik:
    image: traefik:v3.1.2
    container_name: traefik
    restart: always
    networks:
      - proxy-network
    extra_hosts:
      - host.docker.internal:host-gateway # Docker gateway [Linux]
    ports:
      - 80:80/tcp # HTTP for redirect to HTTPS
      - 443:443/tcp # TCP for HTTPS
      - 443:443/udp # TCP and UDP for QUIC
      - 8080:8080/tcp
    volumes:
      # # Mount the Docker socket [Windows: old versions]
      # - type: npipe
      #   source: \\.\pipe\docker_engine\
      #   target: \\.\pipe\docker_engine\

      # Mount the Docker socket [Linux], [Windows: some versions support this]
      - /var/run/docker.sock:/var/run/docker.sock:ro

      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config:/etc/config:ro
