version: "3.9"

networks:
  proxy-network:
    external: false
    name: proxy-network

services:
  traefik:
    image: traefik:v3.1.2
    container_name: traefik
    restart: always
    networks:
      - proxy-network
    ports:
      - 80:80/tcp # HTTP for redirect to HTTPS
      - 443:443/tcp # TCP for HTTPS
      - 443:443/udp # TCP and UDP for QUIC
      - 8080:8080/tcp
    env_file: ../.env
    environment:
      - BASE_DOMAIN=${BASE_DOMAIN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config:/etc/config:ro
