# ================================= NOTE [Warning] ================================= #
# Command line notes:
# docker -H npipe:////./pipe/docker_engine ps -> List all containers (Windows)
# -- For config network -- #
# "host.docker.internal" is not a valid hostname for [Windows]
# in linux use: docker gateway: "172.17.0.1" [Linux]
# or add 'extra_hosts' in docker-compose.yml (ex: host.docker.internal:host-gateway)
# =================================================================================== #

global:
  checkNewVersion: true
  sendAnonymousUsage: true

log:
  level: DEBUG

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

api:
  debug: true
  dashboard: true
  insecure: true

serversTransport:
  insecureSkipVerify: true

entryPoints:
  http:
    address: :80
    # http:
    #   redirections:
    #     entryPoint:
    #       to: https
    #       scheme: https
    #       permanent: false # if false, redirect use 302 status
  https:
    address: :443

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock" # Listen to the UNIX Docker socket [Linux]
    exposedByDefault: false # Only expose container that are explicitly enabled (using label traefik.enabled)
    network: "proxy-network" # Default network to use for connections to all containers.
    # swarmMode: false # Activates the Swarm Mode (instead of standalone Docker). [v3 not support standalone mode]
    # swarmModeRefreshSeconds: "15" # Defines the polling interval (in seconds) in Swarm Mode. [v3 not support standalone mode]
    watch: true # Watch Docker Swarm events
  file:
    debugLogGeneratedTemplate: true # Log the generated configuration template
    directory: "/etc/config" # Load files from the dynamic configuration directory
    watch: true # Watch for modifications
  providersThrottleDuration: "2s" # Configuration reload frequency.
