version: "3.9"

volumes:
  postgres-data: {}
  redis-data: {}
  rabbitmq-data: {}
  vault-data: {}
  elasticsearch-data: {}

networks:
  proxy-network:
    external: false
    name: proxy-network
  server-network:
    driver: bridge

services:
  postgres:
    image: postgres:13.1
    container_name: postgres
    restart: always
    networks:
      - server-network
      - proxy-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6.0.9
    container_name: redis
    restart: always
    networks:
      - server-network
      - proxy-network
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    networks:
      - server-network
      - proxy-network
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: always
    networks:
      - server-network
      - proxy-network
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID:-root}
    volumes:
      - vault-data:/vault/file
    privileged: true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    restart: always
    networks:
      - proxy-network
      - server-network
    ports:
      - 9200:9200 # for REST API
      - 9300:9300 # for inter-node communication
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false # disable security, not recommended for production
    # volumes:
    #   - elasticsearch-data:/usr/share/elasticsearch/data (error: maybe these locations are not writable or multiple nodes were started on the same data path?)
