global:
  smtp_smarthost: ${SMTP_HOST}:${SMTP_PORT}
  smtp_auth_username: ${SMTP_USERNAME}
  smtp_auth_password: ${SMTP_PASSWORD}
  smtp_from: ${SMTP_USERNAME}

route:
  group_by: ["alertname", "cluster", "service"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: "email"

receivers:
  - name: "email"
    email_configs:
      - to: ${ALERT_EMAIL}
        send_resolved: true
