version: "3.7"

networks:
  proxy-network:
    external: false
    name: proxy-network

services:
  client-ui:
    container_name: client-ui
    restart: always
    env_file: ./client-ui/.env
    build:
      context: ./client-ui
      dockerfile: Dockerfile
    networks:
      - proxy-network
    ports:
      - 4173:4173
