# ======================================== NOTE [Warning] ======================================== #
# Traefik dynamic configuration file
# See https://doc.traefik.io/traefik/getting-started/configuration-overview/#the-dynamic-configuration

# -- For config network -- #
# "host.docker.internal" is not a valid hostname for [Windows]
# in linux use: docker gateway: "172.17.0.1" [Linux]

# -- Dynamic Configuration -- #
# FIXME: not working with windows (not reload config)
# =============================================================================================== #

http:
  middlewares:
    latency-check:
      circuitBreaker:
        expression: "LatencyAtQuantileMS(50.0) > 100"

    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        accessControlAllowHeaders: "*"
        accessControlAllowCredentials: true
        accessControlAllowOriginList: "*"
        accessControlMaxAge: 100
        addVaryHeader: true

    rate-limit:
      rateLimit:
        average: 100
        burst: 10
        period: 1s

    forward-auth:
      forwardAuth:
        address: http://localhost/api/v1/auth/validate
        trustForwardHeader: true
        authResponseHeadersRegex: "^X-"
        tls:
          insecureSkipVerify: true

  routers:
    client-ui:
      rule: PathPrefix(`/`)
      service: client-ui
      entrypoints: http

    auth:
      rule: PathRegexp(`^/api/v[0-9]+/auth`)
      service: auth-service
      entrypoints: http
      middlewares:
        - cors

    user:
      rule: PathRegexp(`^/api/v[0-9]+/users`)
      service: auth-service
      entrypoints: http
      middlewares:
        - cors
        - forward-auth

    storage:
      rule: PathRegexp(`^/api/v[0-9]+/storage`)
      service: storage-service
      entrypoints: http
      middlewares:
        - cors
        - forward-auth

  services:
    client-ui:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:5173

    auth-service:
      loadBalancer:
        healthCheck:
          mode: http
          path: /api/health
          interval: 2s
          timeout: 2s
        servers:
          - url: http://host.docker.internal:3000

    storage-service:
      loadBalancer:
        healthCheck:
          mode: http
          path: /api/health
          interval: 2s
          timeout: 2s
        servers:
          - url: http://host.docker.internal:4000
