# Traefik dynamic configuration file
# See https://doc.traefik.io/traefik/getting-started/configuration-overview/#the-dynamic-configuration

tcp:
  routers:
    redis:
      rule: HostSNI(`redis.{{env "BASE_DOMAIN"}}`)
      entryPoints: redis
      service: redis
      tls:
        passthrough: true

    postgres:
      rule: HostSNI(`postgres.{{env "BASE_DOMAIN"}}`)
      entryPoints: postgres
      service: postgres
      tls:
        passthrough: true

  services:
    redis:
      loadBalancer:
        servers:
          - address: "my-redis:6379"
    postgres:
      loadBalancer:
        servers:
          - address: "my-postgres:5432"

http:
  middlewares:
    auth:
      basicAuth:
        usersFile: /etc/config/pass/users.htpasswd

    api-stripPrefix:
      stripPrefix:
        prefixes: ["/identity", "/storage"]

  routers:
    dashboard:
      rule: Host(`traefik.{{env "BASE_DOMAIN"}}`)
      service: api@internal
      entrypoints: https
      middlewares:
        - auth
      tls:
        certResolver: cloudflare

    identity:
      rule: Host(`api.{{env "BASE_DOMAIN"}}`) && PathPrefix(`/identity`)
      service: identity
      entrypoints: https
      middlewares:
        - api-stripPrefix
      tls: {}

    payment:
      rule: Host(`api.{{env "BASE_DOMAIN"}}`) && PathPrefix(`/payment`)
      service: payment
      entrypoints: https
      tls: {}

  services:
    identity:
      loadBalancer:
        servers:
          - url: http://localhost:3000

    payment:
      loadBalancer:
        servers:
          - url: http://localhost:4000
