version: "3.9"

networks:
  proxy-network:
    external: true

services:
  postgres:
    image: postgres:13.3
    container_name: other-postgres
    restart: always
    environment:
      POSTGRES_USER: dangnhatminh
      POSTGRES_PASSWORD: dangnhatminh
      POSTGRES_DB: dangnhatminh
    networks:
      - proxy-network
    ports:
      - 5432:5432

  redis:
    image: redis:6.2.5
    container_name: other-redis
    restart: always
    networks:
      - proxy-network
    ports:
      - 6379:6379
