version: "3.9"

networks:
  proxy-network:
    external: true

volumes:
  portainer_data: {}

services:
  postgres:
    image: postgres:13.1
    container_name: my-postgres
    restart: always
    networks:
      - proxy-network
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:6.0.9
    container_name: my-redis
    restart: always
    networks:
      - proxy-network

  # portainer:
  #   image: portainer/portainer-ce:latest
  #   container_name: my-portainer
  #   restart: always
  #   networks:
  #     - proxy-network
  #   env_file: .env
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data
