version: "3.9"

networks:
  proxy-network:
    external: true

volumes:
  portainer_data: {}
  logstash_pipeline: {}

services:
  postgres:
    image: postgres:13.1
    container_name: my-postgres
    restart: always
    networks:
      - proxy-network
    ports:
      - 5432:5432
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:6.0.9
    container_name: my-redis
    restart: always
    networks:
      - proxy-network
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: my-rabbitmq
    restart: always
    env_file: .env
    networks:
      - proxy-network
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: my-elasticsearch
    restart: always
    networks:
      - proxy-network
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: my-kibana
    restart: always
    networks:
      - proxy-network
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    container_name: my-logstash
    restart: always
    networks:
      - proxy-network
    ports:
      - 5000:5000
    volumes:
      - logstash_pipeline:/usr/share/logstash/pipeline
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  # add filebeat here
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.2
    container_name: my-filebeat
    restart: always
    networks:
      - proxy-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log
    depends_on:
      - logstash
      - elasticsearch
