version: "3.9"

networks:
  proxy-network:
    external: true

services:
  postgres:
    image: postgres:13.1
    container_name: my-postgres
    restart: always
    networks:
      - proxy-network
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
