version: "3.9"

networks:
  proxy-network:
    external: true

volumes:
  portainer_data: {}

services:
  postgres:
    image: postgres:13.1
    container_name: my-postgres
    restart: always
    networks:
      - proxy-network
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:6.0.9
    container_name: my-redis
    restart: always
    networks:
      - proxy-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: my-rabbitmq
    restart: always
    env_file: .env
    networks:
      - proxy-network
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
